/**
 * DisplayData Component - User Management Interface
 * 
 * This component provides a comprehensive interface for displaying, editing, and deleting
 * user data stored in Firestore. It demonstrates CRUD operations with Firebase Firestore v9+
 * and includes proper error handling and loading states.
 * 
 * @fileoverview User data display and management component
 * @author Your Team
 * @version 1.0.0
 */

import React, { useState, useEffect } from 'react';
// Import Firestore database instance from our Firebase configuration
import { db } from '../config/firebase';
// Import Firestore v9+ functions for document and collection operations
import { collection, getDocs, doc, updateDoc, deleteDoc, DocumentData } from 'firebase/firestore';

/**
 * User Data Type Definition
 * 
 * Defines the structure of user data as stored in Firestore.
 * The 'id' field is automatically added when fetching from Firestore.
 */
type User = {
  id: string;    // Unique Firestore document ID (auto-generated by Firestore)
  name: string;  // User's display name
  age: number;   // User's age in years
};

/**
 * DisplayData Functional Component
 * 
 * Renders a list of users with inline editing capabilities and delete functionality.
 * Manages all CRUD operations and provides real-time updates from Firestore.
 * 
 * @returns JSX element containing the user management interface
 */
const DisplayData: React.FC = () => {
  /**
   * Component State Management
   * 
   * These state variables manage the component's data and UI state
   */
  
  // Array of users fetched from Firestore 'users' collection
  const [users, setUsers] = useState<User[]>([]);

  // Object tracking inline name edits for each user (keyed by user.id)
  // This allows independent editing of multiple users simultaneously
  const [editNames, setEditNames] = useState<{ [id: string]: string }>({});
  
  // Object tracking inline age edits for each user (keyed by user.id)
  const [editAges, setEditAges] = useState<{ [id: string]: string }>({});

  // Loading state indicator for async operations
  const [loading, setLoading] = useState<boolean>(true);
  
  // Error state for displaying user-friendly error messages
  const [error, setError] = useState<string | null>(null);

  /**
   * Effect Hook: Fetch Users on Component Mount
   * 
   * This effect runs once when the component mounts and fetches all users
   * from the Firestore 'users' collection. It handles loading states and errors.
   */
  useEffect(() => {
    /**
     * Async function to fetch all users from Firestore
     * 
     * Retrieves all documents from the 'users' collection and maps them
     * to our User type, including the document ID as the user's ID.
     */
    const fetchUsers = async (): Promise<void> => {
      setLoading(true); // Indicate data loading is in progress
      
      try {
        // Get all documents from the 'users' collection
        const querySnapshot = await getDocs(collection(db, 'users'));
        
        // Transform Firestore documents into User objects
        const usersArray = querySnapshot.docs.map((docSnap) => ({
          id: docSnap.id,           // Document ID becomes user ID
          ...docSnap.data(),        // Spread document data (name, age, etc.)
        })) as User[];
        
        setUsers(usersArray);       // Update component state with fetched users
        setError(null);             // Clear any previous errors on success
        
      } catch (err) {
        console.error('Error fetching users:', err);
        setError('Failed to load users. Please try again.');
      } finally {
        setLoading(false);          // Always stop loading indicator
      }
    };

    // Execute the fetch function
    fetchUsers();
  }, []); // Empty dependency array - effect runs only once on mount

  /**
   * Update User Function
   * 
   * Updates specific fields of a user document in Firestore and refreshes the UI.
   * Uses Partial<User> to allow updating only the fields that have changed.
   * 
   * @param userId - Unique identifier of the user to update
   * @param updatedData - Object containing only the fields to update
   */
  const updateUser = async (userId: string, updatedData: Partial<User>): Promise<void> => {
    try {
      // Create reference to the specific user document
      const userDoc = doc(db, 'users', userId);
      
      // Update only the specified fields in Firestore
      await updateDoc(userDoc, updatedData);
      
      // Refresh the user list to reflect changes
      await refetchUsers();
      
      // Clear the edit fields for this user after successful update
      setEditNames(prev => ({ ...prev, [userId]: '' }));
      setEditAges(prev => ({ ...prev, [userId]: '' }));
      
    } catch (err) {
      console.error('Error updating user:', err);
      setError('Failed to update user. Please try again.');
    }
  };

  /**
   * Delete User Function
   * 
   * Removes a user document from Firestore and refreshes the UI.
   * This action is irreversible, so consider adding confirmation dialogs.
   * 
   * @param userId - Unique identifier of the user to delete
   */
  const deleteUser = async (userId: string): Promise<void> => {
    // Optional: Add confirmation dialog here
    if (!window.confirm('Are you sure you want to delete this user?')) {
      return;
    }

    try {
      // Delete the document from Firestore
      await deleteDoc(doc(db, 'users', userId));
      
      // Refresh the user list to reflect the deletion
      await refetchUsers();
      
      // Clean up edit state for the deleted user
      setEditNames(prev => {
        const newState = { ...prev };
        delete newState[userId];
        return newState;
      });
      setEditAges(prev => {
        const newState = { ...prev };
        delete newState[userId];
        return newState;
      });
      
    } catch (err) {
      console.error('Error deleting user:', err);
      setError('Failed to delete user. Please try again.');
    }
  };

  /**
   * Refetch Users Helper Function
   * 
   * Re-fetches all users from Firestore to keep the UI synchronized
   * after update or delete operations. This ensures data consistency.
   */
  const refetchUsers = async (): Promise<void> => {
    setLoading(true);
    
    try {
      // Fetch fresh data from Firestore
      const querySnapshot = await getDocs(collection(db, 'users'));
      
      // Map documents to User objects
      const usersArray = querySnapshot.docs.map((docSnap) => ({
        id: docSnap.id,
        ...docSnap.data(),
      })) as User[];
      
      setUsers(usersArray);
      setError(null);
      
    } catch (err) {
      console.error('Error refreshing users:', err);
      setError('Failed to refresh user data.');
    } finally {
      setLoading(false);
    }
  };

  /**
   * Render Component UI
   * 
   * The component renders different content based on loading and error states,
   * then displays the user management interface when data is ready.
   */

  // Show loading spinner while data is being fetched
  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '20px' }}>
        <p>Loading users...</p>
      </div>
    );
  }

  // Show error message if something went wrong
  if (error) {
    return (
      <div style={{ color: 'red', padding: '20px', textAlign: 'center' }}>
        <p>{error}</p>
        <button onClick={refetchUsers}>Try Again</button>
      </div>
    );
  }

  // Main component render: user management interface
  return (
    <div style={{ padding: '20px' }}>
      <h2>Users Management</h2>
      <p>Total users: {users.length}</p>
      
      {/* Handle empty state */}
      {users.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '40px' }}>
          <p>No users found. Add some users to get started!</p>
        </div>
      ) : (
        /* Render user list with inline editing capabilities */
        <div>
          {users.map((user) => (
            <div 
              key={user.id} 
              style={{ 
                border: '2px solid #ddd', 
                borderRadius: '8px',
                margin: '10px 0', 
                padding: '15px',
                backgroundColor: '#f9f9f9'
              }}
            >
              {/* Display current user information */}
              <div style={{ marginBottom: '15px' }}>
                <h4>User ID: {user.id}</h4>
                <p><strong>Name:</strong> {user.name}</p>
                <p><strong>Age:</strong> {user.age} years old</p>
              </div>

              {/* Inline editing section for user name */}
              <div style={{ marginBottom: '10px' }}>
                <label htmlFor={`name-${user.id}`}>Update Name: </label>
                <input
                  id={`name-${user.id}`}
                  value={editNames[user.id] ?? ''}
                  onChange={(e) =>
                    setEditNames({ ...editNames, [user.id]: e.target.value })
                  }
                  type="text"
                  placeholder="Enter new name"
                  style={{ margin: '0 10px', padding: '5px' }}
                />
                <button 
                  onClick={() => updateUser(user.id, { name: editNames[user.id] ?? '' })}
                  disabled={!editNames[user.id]?.trim()}
                  style={{ 
                    backgroundColor: '#007bff', 
                    color: 'white', 
                    border: 'none', 
                    padding: '5px 10px',
                    borderRadius: '4px',
                    cursor: 'pointer'
                  }}
                >
                  Update Name
                </button>
              </div>

              {/* Inline editing section for user age */}
              <div style={{ marginBottom: '15px' }}>
                <label htmlFor={`age-${user.id}`}>Update Age: </label>
                <input
                  id={`age-${user.id}`}
                  value={editAges[user.id] ?? ''}
                  onChange={(e) =>
                    setEditAges({ ...editAges, [user.id]: e.target.value })
                  }
                  type="number"
                  min="0"
                  max="150"
                  placeholder="Enter new age"
                  style={{ margin: '0 10px', padding: '5px', width: '80px' }}
                />
                <button 
                  onClick={() => updateUser(user.id, { age: Number(editAges[user.id]) })}
                  disabled={!editAges[user.id] || isNaN(Number(editAges[user.id]))}
                  style={{ 
                    backgroundColor: '#28a745', 
                    color: 'white', 
                    border: 'none', 
                    padding: '5px 10px',
                    borderRadius: '4px',
                    cursor: 'pointer'
                  }}
                >
                  Update Age
                </button>
              </div>

              {/* Delete user button with warning styling */}
              <div>
                <button
                  style={{ 
                    backgroundColor: '#dc3545', 
                    color: 'white', 
                    border: 'none', 
                    padding: '8px 15px',
                    borderRadius: '4px',
                    cursor: 'pointer',
                    fontWeight: 'bold'
                  }}
                  onClick={() => deleteUser(user.id)}
                >
                  🗑️ Delete User
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default DisplayData;